<a href="https://colab.research.google.com/github/adamKuzanski/Adam-/blob/master/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


'1.18.2'

**1D array**

In [9]:
x = np.array([1, 3])
print(x)
print(type(x))
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

[1 3]
<class 'numpy.ndarray'>
1
(2,)
2
int64


In [10]:
x = np.array([1.3, 2.3, 1.4])
x.dtype

dtype('float64')

2D **Array**

In [14]:
y = np.array([[1,2,3], [-3,-1,-1]])
y

array([[ 1,  2,  3],
       [-3, -1, -1]])

In [17]:
y.shape

(2, 3)

**3D Array**

In [22]:
x = np.array( 
    [
     [[1,2,4], [4,2,1]], 
      [[1,2,3], [9,9,9]] 
     ] 
    )

print(x.ndim)
print(x.shape)

(2, 2, 3)

**Typy danych**

In [26]:
A = np.array([1, 2, 3], dtype='float')
print(A.dtype)

A = np.array([1, 2, 3], dtype='complex')
print(A.dtype)

A = np.array([1.0, 2.2, 3.6], dtype='int')
print(A.dtype)
print(A)

A = np.array([True, False, False], dtype='bool')
print(A.dtype)

A = np.array([24,120,230], dtype=np.uint)
print(A.dtype)

float64
complex128
int64
[1 2 3]
bool
uint64


**Tworzenie Tablic**

In [35]:
np.zeros(shape=(2, 3, 4), dtype='int')

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [36]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.full(shape=(4,4), fill_value=5, dtype='int')

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [38]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.arange(start=10, stop=100, step=0.05)

array([10.  , 10.05, 10.1 , ..., 99.85, 99.9 , 99.95])

In [45]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [53]:
A = np.arange(15)
# A = A.reshape((3,5))
A = A.reshape((3, -1))
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**Działania na tablicach**

In [55]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [56]:
A + B

array([6, 0, 7, 4])

In [57]:
A - B

array([0, 2, 1, 0])

In [58]:
A * B

array([ 9, -1, 12,  4])

In [59]:
A / 2

array([1.5, 0.5, 2. , 1. ])

In [61]:
A + 3 #doda stałą

array([6, 4, 7, 5])

In [63]:
A + 3*B

array([12, -2, 13,  8])

In [65]:
print(np.add(A, B))
print(np.subtract(A, B))
print(np.multiply(A, B))
print(np.divide(A, B))


[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [76]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])

print("Mnożenie element po elemencie")
print(X * Y)
print('\n')

print("Mnożenie macieży")
print(np.dot(X, Y))
print('\n')
print(np.dot(Y, X))
print('\n')
print(X.dot(Y))
print('\n')
print( X @ Y)
print('\n')

Mnożenie element po elemencie
[[6 0]
 [2 0]]


Mnożenie macieży
[[  3   6]
 [-12   0]]


[[ 6 18]
 [-5 -3]]


[[  3   6]
 [-12   0]]


[[  3   6]
 [-12   0]]


